"""Minimal end-to-end demo for the frozen v0.1 MVP.

This script demonstrates the current closed loop without adding any new
protocol fields or touching the real OpenClaw trigger layer:

raw_input
-> FlowManager generates candidate payload
-> user revision
-> confirm
-> SQLite persistence
-> fetch by bundle_id

It intentionally distinguishes:
- flow_session: in-memory session returned by FlowManager.start_session()
- db_session_id: persisted session_id returned by db.insert_flow_session()

They may look similar, but the demo does not assume they are the same object
or the same identity source.
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import db  # noqa: E402
from flow_manager import FLOW_STATES, FlowManager  # noqa: E402
from validator import validate_candidate_payload  # noqa: E402


STRUCTURED_RAW_INPUT = """[FSYQ 结构化录入]

1. 事件：推进了协议字段整理 45分钟
2. 状态：有点疲劳但还能专注
3. 时间：今晚九点左右

主通道标签：6
副通道标签：
主价值标签：1
副属性标签：
"""

STRUCTURED_REVISION = """[FSYQ 结构化录入]

1. 事件：推进了协议字段整理与校验规则 45分钟
2. 状态：有点疲劳但还能专注
3. 时间：2026-03-30 21:00

主通道标签：6
副通道标签：
主价值标签：1
副属性标签：
"""

NATURAL_RAW_INPUT = "今晚九点左右处理了不得不做的杂务，感觉有点累"
NATURAL_REVISION = "2026-03-30 21:00 处理了不得不做的杂务，感觉有点累"


def main() -> None:
    """Run two demo cases against one temporary SQLite database."""
    with tempfile.TemporaryDirectory(prefix="negative_entropy_demo_") as tmp_dir:
        db_path = Path(tmp_dir) / "demo.sqlite3"
        schema_path = PROJECT_ROOT / "sql" / "schema.sql"

        print(f"[setup] database path: {db_path}")
        conn = db.connect_db(str(db_path))
        try:
            print("[setup] init schema.sql")
            db.init_db(conn, str(schema_path))

            manager = FlowManager()

            run_demo_case(
                conn=conn,
                manager=manager,
                case_name="A. 结构化模板输入",
                raw_input=STRUCTURED_RAW_INPUT,
                revision_text=STRUCTURED_REVISION,
            )

            run_demo_case(
                conn=conn,
                manager=manager,
                case_name="B. 自然语言输入",
                raw_input=NATURAL_RAW_INPUT,
                revision_text=NATURAL_REVISION,
            )

            print("\n[done] all demo cases passed.")
        finally:
            conn.close()


def run_demo_case(
    conn,
    manager: FlowManager,
    case_name: str,
    raw_input: str,
    revision_text: str,
) -> None:
    """Run one closed-loop case and assert every frozen requirement we can observe."""
    print(f"\n=== {case_name} ===")

    observed_flow_states: list[str] = []

    # 1. FlowManager.start_session(): create an in-memory flow session.
    flow_session = manager.start_session(raw_input)
    observed_flow_states.append(flow_session["flow_state"])
    _assert_valid_flow_state(flow_session["flow_state"])
    print(f"[1] flow_session started: {flow_session['session_id']} ({flow_session['flow_state']})")

    # 2. db.insert_flow_session(): persist the raw input as a DB session.
    # This db_session_id is generated by the database layer and must be treated
    # as distinct from the in-memory flow_session identity.
    db_session_id = db.insert_flow_session(
        conn,
        raw_input=raw_input,
        candidate_payload=None,
        flow_state="awaiting_input",
        last_user_revision=None,
    )
    _assert_valid_flow_state("awaiting_input")
    print(f"[2] db_session inserted: {db_session_id} (separate from flow_session)")

    # 3. FlowManager.parse_session(): parse raw_input into a validated payload.
    parsed_session = manager.parse_session(flow_session)
    parsed_payload = parsed_session["candidate_payload"]
    observed_flow_states.append(parsed_session["flow_state"])
    _assert_valid_flow_state(parsed_session["flow_state"])
    _assert_payload_is_valid(parsed_payload)
    print(f"[3] parsed candidate payload bundle_id: {parsed_payload['bundle_id']}")

    # 4. db.update_candidate_payload(..., flow_state="awaiting_confirmation"):
    # Store the first candidate version in the DB session.
    db.update_candidate_payload(
        conn,
        session_id=db_session_id,
        candidate_payload=parsed_payload,
        last_user_revision=None,
        flow_state="awaiting_confirmation",
    )
    _assert_valid_flow_state("awaiting_confirmation")
    print("[4] first candidate payload saved to flow_sessions.candidate_payload")

    # 5. FlowManager.apply_user_revision(): re-parse using the revision text.
    revised_session = manager.apply_user_revision(parsed_session, revision_text)
    revised_payload = revised_session["candidate_payload"]
    observed_flow_states.append(revised_session["flow_state"])
    _assert_valid_flow_state(revised_session["flow_state"])
    _assert_payload_is_valid(revised_payload)
    print(f"[5] revised payload bundle_id preserved: {revised_payload['bundle_id']}")

    # 6. db.update_candidate_payload(..., last_user_revision=..., flow_state="awaiting_confirmation"):
    # Overwrite DB candidate_payload with the latest revision.
    db.update_candidate_payload(
        conn,
        session_id=db_session_id,
        candidate_payload=revised_payload,
        last_user_revision=revision_text,
        flow_state="awaiting_confirmation",
    )
    print("[6] latest revised candidate payload overwritten in DB")

    # 7. FlowManager.confirm_candidates(): validate one more time and commit in memory.
    committed_session = manager.confirm_candidates(revised_session)
    final_payload = committed_session["candidate_payload"]
    observed_flow_states.append(committed_session["flow_state"])
    _assert_valid_flow_state(committed_session["flow_state"])
    _assert_payload_is_valid(final_payload)
    print(f"[7] in-memory flow confirmed: {committed_session['flow_state']}")

    # 8. db.update_flow_session_state(..., "committed"): persist the final state.
    db.update_flow_session_state(conn, db_session_id, "committed")
    _assert_valid_flow_state("committed")
    print("[8] DB flow_state updated to committed")

    # 9. Confirm the DB really stores the latest revised candidate JSON.
    stored_session = conn.execute(
        """
        SELECT session_id, raw_input, last_user_revision, candidate_payload, flow_state
        FROM flow_sessions
        WHERE session_id = ?
        """,
        (db_session_id,),
    ).fetchone()
    if stored_session is None:
        raise AssertionError("flow_sessions row was not found after update.")

    stored_payload = json.loads(stored_session["candidate_payload"])
    if stored_payload != final_payload:
        raise AssertionError("flow_sessions.candidate_payload is not the latest revised version.")
    if stored_session["last_user_revision"] != revision_text:
        raise AssertionError("last_user_revision was not persisted as the latest revision.")
    if stored_session["flow_state"] != "committed":
        raise AssertionError("flow_sessions.flow_state is not committed after final update.")
    print("[9] DB session stores the latest revised candidate payload")

    # 10. db.insert_records(...): persist the final candidate records.
    bundle_id, record_ids = db.insert_records(
        conn,
        bundle_id=final_payload["bundle_id"],
        records=final_payload["records"],
    )
    print(f"[10] inserted {len(record_ids)} records into bundle {bundle_id}")

    # 11. db.fetch_records_by_bundle(...): query back the bundle and verify storage invariants.
    fetched_records = db.fetch_records_by_bundle(conn, bundle_id)
    print(f"[11] fetched {len(fetched_records)} records by bundle_id")

    _assert_demo_requirements(
        final_payload=final_payload,
        fetched_records=fetched_records,
        observed_flow_states=observed_flow_states,
    )

    print("[12] demo checks passed")
    print("     flow_session_id:", flow_session["session_id"])
    print("     db_session_id:  ", db_session_id)
    print("     record_ids:     ", ", ".join(record_ids))


def _assert_payload_is_valid(candidate_payload: dict[str, Any]) -> None:
    errors = validate_candidate_payload(candidate_payload)
    if errors:
        raise AssertionError(f"candidate payload is invalid: {'; '.join(errors)}")


def _assert_valid_flow_state(flow_state: str) -> None:
    if flow_state not in FLOW_STATES:
        raise AssertionError(f"illegal flow_state observed: {flow_state}")


def _assert_demo_requirements(
    final_payload: dict[str, Any],
    fetched_records: list[dict[str, Any]],
    observed_flow_states: list[str],
) -> None:
    """Assert the exact acceptance criteria required by the demo module."""
    if validate_candidate_payload(final_payload) != []:
        raise AssertionError("final candidate_payload failed validate_candidate_payload(candidate_payload) == []")

    for flow_state in observed_flow_states:
        _assert_valid_flow_state(flow_state)

    if len(fetched_records) != len(final_payload["records"]):
        raise AssertionError("persisted record count does not match final candidate_payload.records length.")

    for record in fetched_records:
        if record["source"] != "openclaw":
            raise AssertionError("records.source must be fixed to openclaw.")
        if isinstance(record["related_to"], str) and record["related_to"].startswith("temp_"):
            raise AssertionError("records.related_to must not retain temp_n after persistence.")


if __name__ == "__main__":
    main()
